dataset_name: 'CoauthorCS'
architecture: 'ARMA'
test: True
use_lcc: True
num_development: 5000
num_per_class: 20

none:
  hidden_layers: 1
  hidden_units: 16
  lr: 0.01
  dropout: 0.5
  weight_decay: 0.02
  stacks: 2

heat:
  hidden_layers: 1
  hidden_units: 16
  dropout: 0.5
  lr: 0.01
  weight_decay: 0.01
  t: 1.0
  k: 64
  eps: 
  stacks: 3