dataset_name: 'Citeseer'
architecture: 'JKNet'
test: True
use_lcc: True
num_development: 1500
num_per_class: 20

none:
  hidden_layers: 4
  hidden_units: 64
  lr: 0.01
  dropout: 0.5
  weight_decay: 1

heat:
  hidden_layers: 2
  hidden_units: 64
  dropout: 0.5
  lr: 0.01
  weight_decay: 1.00
  t: 4.0
  k:
  eps: 0.0009