dataset_name: 'Citeseer'
architecture: 'ARMA'
test: True
use_lcc: True
num_development: 1500
num_per_class: 20

none:
  hidden_layers: 1
  hidden_units: 16
  lr: 0.01
  dropout: 0.5
  weight_decay: 0.04
  stacks: 3